import type { Metadata } from "next"
import { createMetadata } from "@/lib/metadata"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowLeft, Heart, Shield, Sparkles, Users } from 'lucide-react'

export const metadata: Metadata = createMetadata({
  title: "About Us - AI Kids Learning Platform",
  description:
    "Learn about our mission to make AI accessible and fun for children ages 5-12. Discover how we're empowering the next generation with interactive AI education.",
  path: "/about",
})

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 relative overflow-hidden">
      {/* AI-themed floating decorative emojis */}
      <div className="absolute top-20 right-20 text-6xl opacity-20 animate-float" style={{ filter: 'drop-shadow(0 4px 8px rgba(147, 51, 234, 0.3))' }}>🤖</div>
      <div className="absolute top-60 left-10 text-5xl opacity-20 animate-pulse" style={{ filter: 'drop-shadow(0 4px 8px rgba(236, 72, 153, 0.3))' }}>🧠</div>
      <div className="absolute bottom-40 right-1/4 text-4xl opacity-20 animate-bounce" style={{ filter: 'drop-shadow(0 4px 8px rgba(59, 130, 246, 0.3))' }}>💻</div>

      <div className="max-w-4xl mx-auto px-4 py-12 relative z-10">
        <Link href="/">
          <Button variant="ghost" className="mb-6 rounded-full">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Home
          </Button>
        </Link>

        <div className="bg-white/80 backdrop-blur-md rounded-3xl shadow-2xl p-8 md:p-12 border-2 border-purple-200">
          <div className="text-center mb-12">
            <div className="text-7xl mb-4 animate-bounce">🚀</div>
            <h1 className="text-4xl font-bold mb-4 bg-gradient-to-r from-purple-600 via-pink-500 to-blue-600 bg-clip-text text-transparent">
              About AI Kids Learning Platform
            </h1>
            <p className="text-xl text-gray-600">Where Young Minds Meet Artificial Intelligence</p>
          </div>

          <div className="space-y-8 text-gray-700">
            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-900">Our Mission</h2>
              <p className="text-lg leading-relaxed">
                We believe that every child deserves to understand the technology shaping their future. Our mission is
                to make artificial intelligence accessible, understandable, and fun for children through interactive
                learning experiences that spark curiosity and build confidence.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-900">What We Offer</h2>
              <div className="grid md:grid-cols-2 gap-6">
                <div className="bg-gradient-to-br from-blue-100 to-cyan-100 p-6 rounded-2xl border-2 border-blue-200 hover:scale-105 transition-transform">
                  <div className="text-3xl mb-3">🎮</div>
                  <h3 className="font-bold text-lg mb-2">Interactive Games</h3>
                  <p className="text-sm">
                    Engaging AI-powered games that teach concepts like pattern recognition, decision-making, and
                    problem-solving through play.
                  </p>
                </div>

                <div className="bg-gradient-to-br from-purple-100 to-violet-100 p-6 rounded-2xl border-2 border-purple-200 hover:scale-105 transition-transform">
                  <div className="text-3xl mb-3">📚</div>
                  <h3 className="font-bold text-lg mb-2">AI Storytelling</h3>
                  <p className="text-sm">
                    Personalized stories generated by AI that adapt to your child's interests and reading level, making
                    learning magical.
                  </p>
                </div>

                <div className="bg-gradient-to-br from-pink-100 to-rose-100 p-6 rounded-2xl border-2 border-pink-200 hover:scale-105 transition-transform">
                  <div className="text-3xl mb-3">🤖</div>
                  <h3 className="font-bold text-lg mb-2">AI Friends</h3>
                  <p className="text-sm">
                    Safe, educational conversations with AI companions that answer questions and encourage curiosity
                    about the world.
                  </p>
                </div>

                <div className="bg-gradient-to-br from-orange-100 to-yellow-100 p-6 rounded-2xl border-2 border-orange-200 hover:scale-105 transition-transform">
                  <div className="text-3xl mb-3">🏆</div>
                  <h3 className="font-bold text-lg mb-2">Progress Tracking</h3>
                  <p className="text-sm">
                    Comprehensive parent dashboard with detailed analytics, achievements, and insights into your child's
                    learning journey.
                  </p>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-900">Our Values</h2>
              <div className="space-y-4">
                <div className="flex gap-4">
                  <div className="flex-shrink-0">
                    <Shield className="h-8 w-8 text-blue-600" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg mb-1">Safety First</h3>
                    <p>
                      We prioritize child safety with COPPA-compliant practices, content filtering, and parental
                      controls. Your child's data is protected with industry-leading security measures.
                    </p>
                  </div>
                </div>

                <div className="flex gap-4">
                  <div className="flex-shrink-0">
                    <Heart className="h-8 w-8 text-pink-600" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg mb-1">Age-Appropriate Learning</h3>
                    <p>
                      All content is carefully designed for children aged 6-12, with age-appropriate language, concepts,
                      and interactions that match developmental stages.
                    </p>
                  </div>
                </div>

                <div className="flex gap-4">
                  <div className="flex-shrink-0">
                    <Sparkles className="h-8 w-8 text-purple-600" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg mb-1">Fun & Engaging</h3>
                    <p>
                      Learning should be exciting! We use gamification, rewards, and interactive experiences to keep
                      children motivated and engaged in their AI education journey.
                    </p>
                  </div>
                </div>

                <div className="flex gap-4">
                  <div className="flex-shrink-0">
                    <Users className="h-8 w-8 text-orange-600" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg mb-1">Parent Partnership</h3>
                    <p>
                      We empower parents with tools to monitor progress, understand their child's learning, and be
                      active participants in their educational journey.
                    </p>
                  </div>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-900">Why AI Education Matters</h2>
              <p className="leading-relaxed mb-4">
                Artificial Intelligence is transforming every aspect of our lives, from how we work to how we
                communicate. Today's children will grow up in a world where AI is ubiquitous, and understanding these
                technologies is no longer optional—it's essential.
              </p>
              <p className="leading-relaxed">
                By introducing AI concepts early through play and exploration, we're not just teaching technology—we're
                building critical thinking skills, fostering creativity, and preparing children to be informed,
                confident participants in an AI-powered future.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-900">Our Technology</h2>
              <p className="leading-relaxed mb-4">
                We use cutting-edge AI technology from trusted providers to deliver safe, educational experiences:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Advanced natural language processing for conversations and storytelling</li>
                <li>Content filtering and safety measures to ensure age-appropriate interactions</li>
                <li>Adaptive learning algorithms that personalize content to each child</li>
                <li>Secure, encrypted data storage and transmission</li>
                <li>Regular updates and improvements based on educational research</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-900">Get Started Today</h2>
              <p className="leading-relaxed mb-6">
                Join thousands of families who are discovering the joy of AI learning. Start with our free tier to
                explore the platform, or upgrade to Premium for unlimited access to all features.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Link href="/auth/sign-up">
                  <Button size="lg" className="w-full sm:w-auto">
                    Create Free Account
                  </Button>
                </Link>
                <Link href="/pricing">
                  <Button size="lg" variant="outline" className="w-full sm:w-auto bg-transparent">
                    View Pricing
                  </Button>
                </Link>
              </div>
            </section>

            <section className="border-t pt-8">
              <h2 className="text-2xl font-semibold mb-4 text-gray-900">Contact Us</h2>
              <p className="leading-relaxed mb-4">Have questions or feedback? We'd love to hear from you!</p>
              <Link href="/contact">
                <Button variant="outline">Get in Touch</Button>
              </Link>
            </section>
          </div>
        </div>
      </div>

      <div className="relative h-32 mt-12">
        <svg className="absolute bottom-0 w-full" viewBox="0 0 1440 120" preserveAspectRatio="none">
          <path
            d="M0,32 C320,96 640,96 960,32 C1280,0 1600,0 1440,32 L1440,120 L0,120 Z"
            fill="white"
            opacity="0.8"
          />
        </svg>
      </div>
    </div>
  )
}
