-- Seed initial courses for AI for Kids platform
INSERT INTO courses (slug, title, description, long_description, age_min, age_max, difficulty, duration_minutes, lessons_count, price, currency, learning_outcomes, thumbnail_url, is_published, category, curriculum)
VALUES
(
  'ai-basics-for-kids',
  'AI osnove za otroke',
  'Zabaven uvod v svet umetne inteligence za otroke od 6 do 10 let. Interaktivne lekcije z igrami in kvizi.',
  'Ta tečaj je zasnovan posebej za mlajše otroke, ki želijo razumeti, kaj je umetna inteligenca in kako deluje v vsakdanjem življenju. Skozi zabavne igre, zgodbe in interaktivne vaje bodo otroci spoznali osnove AI na razumljiv in privlačen način. Vsaka lekcija vključuje praktične primere iz resničnega življenja, ki jih otroci lahko prepoznajo - od pametnih asistentov do priporočilnih sistemov v njihovih najljubših aplikacijah.',
  6, 10,
  'beginner',
  480,
  12,
  1990,
  'eur',
  '["Razumevanje kaj je AI", "Prepoznavanje AI v vsakdanjem življenju", "Osnove strojnega učenja skozi igro", "Kritično razmišljanje o tehnologiji"]',
  '/images/courses/ai-basics.jpg',
  true,
  'ai',
  '[{"title": "Kaj je AI?", "lessons": 3}, {"title": "AI okrog nas", "lessons": 3}, {"title": "Kako se AI uči", "lessons": 3}, {"title": "Ustvarjajmo z AI", "lessons": 3}]'
),
(
  'coding-with-ai',
  'Programiranje z AI',
  'Naučite se osnov programiranja s pomočjo umetne inteligence. Za otroke od 8 do 14 let.',
  'V tem tečaju se otroci naučijo osnov programiranja skozi praktične projekte, ki vključujejo umetno inteligenco. Od enostavnih ukazov do ustvarjanja lastnih mini AI projektov - vsak korak je prilagojen otrokovi starosti in predznanju. Tečaj uporablja vizualno programiranje za mlajše in postopno uvaja tekstovno programiranje za starejše otroke.',
  8, 14,
  'intermediate',
  900,
  20,
  2990,
  'eur',
  '["Osnove programiranja", "Ustvarjanje preprostih AI projektov", "Logično razmišljanje", "Reševanje problemov s kodo", "Razumevanje algoritmov"]',
  '/images/courses/coding-ai.jpg',
  true,
  'coding',
  '[{"title": "Uvod v programiranje", "lessons": 5}, {"title": "Vizualno programiranje", "lessons": 5}, {"title": "AI projekti", "lessons": 5}, {"title": "Moj prvi chatbot", "lessons": 5}]'
),
(
  'ai-art-studio',
  'AI umetniški studio',
  'Ustvarjajte umetnost s pomočjo AI orodij. Kreativni tečaj za otroke od 7 do 12 let.',
  'Kreativnost sreča tehnologijo v tem edinstvenem tečaju, kjer otroci odkrivajo, kako umetna inteligenca lahko pomaga pri ustvarjanju umetnosti. Od generiranja slik do glasbenega ustvarjanja - otroci bodo raziskovali meje med človeško kreativnostjo in strojnim učenjem.',
  7, 12,
  'beginner',
  360,
  10,
  1490,
  'eur',
  '["Uporaba AI za ustvarjanje umetnosti", "Razumevanje generativne AI", "Razvoj kreativnosti", "Digitalna pismenost"]',
  '/images/courses/ai-art.jpg',
  true,
  'creativity',
  '[{"title": "Uvod v AI umetnost", "lessons": 3}, {"title": "Generiranje slik", "lessons": 3}, {"title": "Glasba in AI", "lessons": 2}, {"title": "Moj AI portfolio", "lessons": 2}]'
),
(
  'robotics-and-ai',
  'Robotika in AI',
  'Odkrijte svet robotike in umetne inteligence. Napredni tečaj za otroke od 10 do 16 let.',
  'Ta napredni tečaj povezuje koncepte robotike z umetno inteligenco. Otroci se naučijo, kako roboti razmišljajo, kako se učijo iz okolja in kako sprejemajo odločitve. Tečaj uporablja simulacije in virtualne robote, ki jih otroci programirajo in učijo.',
  10, 16,
  'advanced',
  1200,
  25,
  3990,
  'eur',
  '["Osnove robotike", "Strojno učenje v praksi", "Senzorji in aktuatorji", "Avtonomno odločanje", "STEM veščine"]',
  '/images/courses/robotics-ai.jpg',
  true,
  'robotics',
  '[{"title": "Uvod v robotiko", "lessons": 5}, {"title": "Senzorji in okolje", "lessons": 5}, {"title": "AI za robote", "lessons": 5}, {"title": "Avtonomni roboti", "lessons": 5}, {"title": "Moj robot projekt", "lessons": 5}]'
),
(
  'ai-safety-ethics',
  'AI varnost in etika',
  'Naučite otroke odgovorne uporabe AI. Tečaj za starše in otroke od 8 do 14 let.',
  'V svetu, kjer je AI vse bolj prisotna, je ključno, da otroci razumejo ne le, kako AI deluje, ampak tudi, kako jo uporabljati odgovorno. Ta tečaj pokriva teme kot so zasebnost podatkov, pristranskost v AI sistemih, digitalna varnost in etične dileme umetne inteligence.',
  8, 14,
  'beginner',
  300,
  8,
  990,
  'eur',
  '["Odgovorna uporaba AI", "Razumevanje zasebnosti podatkov", "Prepoznavanje pristranskosti AI", "Digitalna varnost", "Kritično razmišljanje"]',
  '/images/courses/ai-safety.jpg',
  true,
  'safety',
  '[{"title": "Zasebnost in AI", "lessons": 2}, {"title": "Pristranskost v AI", "lessons": 2}, {"title": "Digitalna varnost", "lessons": 2}, {"title": "Etika AI", "lessons": 2}]'
)
ON CONFLICT (slug) DO NOTHING;
