-- Seed initial courses for AI for Kids platform
INSERT INTO courses (slug, title, description, long_description, age_range, difficulty, duration_hours, lessons_count, price_cents, currency, features, learning_outcomes, thumbnail_url, is_published)
VALUES
(
  'ai-basics-for-kids',
  'AI osnove za otroke',
  'Zabaven uvod v svet umetne inteligence za otroke od 6 do 10 let. Interaktivne lekcije z igrami in kvizi.',
  'Ta tečaj je zasnovan posebej za mlajše otroke, ki želijo razumeti, kaj je umetna inteligenca in kako deluje v vsakdanjem življenju. Skozi zabavne igre, zgodbe in interaktivne vaje bodo otroci spoznali osnove AI na razumljiv in privlačen način. Vsaka lekcija vključuje praktične primere iz resničnega življenja, ki jih otroci lahko prepoznajo - od pametnih asistentov do priporočilnih sistemov v njihovih najljubših aplikacijah.',
  '6-10',
  'zacetnik',
  8,
  12,
  1990,
  'EUR',
  '["12 interaktivnih lekcij", "Igre in kvizi", "Certifikat ob zaključku", "Dostop za vedno", "Starševski nadzor napredka"]',
  '["Razumevanje kaj je AI", "Prepoznavanje AI v vsakdanjem življenju", "Osnove strojnega učenja skozi igro", "Kritično razmišljanje o tehnologiji"]',
  '/images/courses/ai-basics.jpg',
  true
),
(
  'coding-with-ai',
  'Programiranje z AI',
  'Naučite se osnov programiranja s pomočjo umetne inteligence. Za otroke od 8 do 14 let.',
  'V tem tečaju se otroci naučijo osnov programiranja skozi praktične projekte, ki vključujejo umetno inteligenco. Od enostavnih ukazov do ustvarjanja lastnih mini AI projektov - vsak korak je prilagojen otrokovi starosti in predznanju. Tečaj uporablja vizualno programiranje za mlajše in postopno uvaja tekstovno programiranje za starejše otroke. Otroci bodo ustvarili lastne chatbote, preproste klasifikatorje slik in interaktivne zgodbe.',
  '8-14',
  'srednji',
  15,
  20,
  2990,
  'EUR',
  '["20 praktičnih lekcij", "Projekti z resnično AI", "Video tutoriali", "Certifikat ob zaključku", "Dostop za vedno", "Skupnost za učence"]',
  '["Osnove programiranja", "Ustvarjanje preprostih AI projektov", "Logično razmišljanje", "Reševanje problemov s kodo", "Razumevanje algoritmov"]',
  '/images/courses/coding-ai.jpg',
  true
),
(
  'ai-art-studio',
  'AI umetniški studio',
  'Ustvarjajte umetnost s pomočjo AI orodij. Kreativni tečaj za otroke od 7 do 12 let.',
  'Kreativnost sreča tehnologijo v tem edinstvenem tečaju, kjer otroci odkrivajo, kako umetna inteligenca lahko pomaga pri ustvarjanju umetnosti. Od generiranja slik do glasbenega ustvarjanja - otroci bodo raziskovali meje med človeško kreativnostjo in strojnim učenjem. Tečaj spodbuja umetniško izražanje, hkrati pa uči otroke, kako AI orodja delujejo v ozadju.',
  '7-12',
  'zacetnik',
  6,
  10,
  1490,
  'EUR',
  '["10 kreativnih lekcij", "AI orodja za umetnost", "Galerija projektov", "Certifikat ob zaključku", "Dostop za vedno"]',
  '["Uporaba AI za ustvarjanje umetnosti", "Razumevanje generativne AI", "Razvoj kreativnosti", "Digitalna pismenost"]',
  '/images/courses/ai-art.jpg',
  true
),
(
  'robotics-and-ai',
  'Robotika in AI',
  'Odkrijte svet robotike in umetne inteligence. Napredni tečaj za otroke od 10 do 16 let.',
  'Ta napredni tečaj povezuje koncepte robotike z umetno inteligenco. Otroci se naučijo, kako roboti "razmišljajo", kako se učijo iz okolja in kako sprejemajo odločitve. Čeprav ne potrebujete fizičnega robota, tečaj uporablja simulacije in virtualne robote, ki jih otroci programirajo in učijo. Idealno za otroke, ki jih zanima STEM in želijo poglobiti svoje znanje o tehnologiji prihodnosti.',
  '10-16',
  'napreden',
  20,
  25,
  3990,
  'EUR',
  '["25 poglobljenih lekcij", "Virtualne simulacije robotov", "Projekti strojnega učenja", "Certifikat ob zaključku", "Dostop za vedno", "Mentorska podpora", "Skupnost za učence"]',
  '["Osnove robotike", "Strojno učenje v praksi", "Senzorji in aktuatorji", "Avtonomno odločanje", "STEM veščine"]',
  '/images/courses/robotics-ai.jpg',
  true
),
(
  'ai-safety-ethics',
  'AI varnost in etika',
  'Naučite otroke odgovorne uporabe AI. Za starše in otroke od 8 do 14 let.',
  'V svetu, kjer je AI vse bolj prisotna, je ključno, da otroci razumejo ne le, kako AI deluje, ampak tudi, kako jo uporabljati odgovorno. Ta tečaj pokriva teme kot so zasebnost podatkov, pristranskost v AI sistemih, digitalna varnost in etične dileme umetne inteligence. Zasnovan je za skupno učenje staršev in otrok, kar spodbuja pomembne družinske pogovore o tehnologiji.',
  '8-14',
  'zacetnik',
  5,
  8,
  990,
  'EUR',
  '["8 lekcij za starše in otroke", "Družinske aktivnosti", "Praktični nasveti za varnost", "Certifikat ob zaključku", "Dostop za vedno"]',
  '["Odgovorna uporaba AI", "Razumevanje zasebnosti podatkov", "Prepoznavanje pristranskosti AI", "Digitalna varnost", "Kritično razmišljanje"]',
  '/images/courses/ai-safety.jpg',
  true
)
ON CONFLICT (slug) DO NOTHING;
