-- Update Robotics and AI course content: fix grammar, improve readability
-- Course: robotics-and-ai (25 lessons, 5 modules x 5)

-- Module 1, Lesson 0: Kaj je robot?
UPDATE course_lessons
SET content = E'# Kaj je robot?\n\nRobot je naprava, ki lahko **zazna** okolje, **razmišlja** o tem, kaj zazna, in **ukrepa** na podlagi svojih odločitev.\n\n---\n\n## Trije deli vsakega robota\n\n### 1. Senzorji (čutila)\n\nSenzorji so kot robotova čutila. Kamere so njegove oči, mikrofoni so ušesa, senzorji pritiska pa njegov dotik.\n\n### 2. Procesor (možgani)\n\nProcesor je robotov mozeg. Tu se izvaja program, ki sprejema odločitve na podlagi informacij iz senzorjev.\n\n### 3. Aktuatorji (mišice)\n\nAktuatorji so robotove mišice -- motorji, ki premikajo roke, kolesa ali druge dele.\n\n---\n\n## Primeri robotov\n\n- **Industrijski roboti** -- sestavljajo avtomobile v tovarnah.\n- **Kirurški roboti** -- pomagajo zdravnikom pri operacijah.\n- **Raziskovalni roboti** -- kot rover na Marsu.\n- **Domači roboti** -- sesalniki kot Roomba.\n\n---\n\n## Razmisli\n\nAli je pametni telefon robot? Ima senzorje (kamero, mikrofon) in procesor, toda nima aktuatorjev za gibanje. Zato ni pravi robot, je pa **pameten** aparat!\n\n---\n\n## Naloga\n\nNariši svojega sanjskega robota. Označi njegove senzorje, procesor in aktuatorje. Kakšno nalogo bi opravljal?',
    updated_at = NOW()
WHERE title = 'Kaj je robot?'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 1, Lesson 1: Zgodovina robotike
UPDATE course_lessons
SET content = E'# Zgodovina robotike\n\nBeseda "robot" izvira iz češke besede **"robota"**, ki pomeni prisilno delo. Prvič jo je uporabil pisatelj Karel Čapek leta 1920.\n\n---\n\n## Mejniki v zgodovini\n\n### Antika in srednji vek\n\n- Stari Grki so gradili **avtomatone** -- mehanske figure, ki so se premikale.\n- Leonardo da Vinci je zasnoval mehanskega viteza leta 1495.\n\n### 20. stoletje\n\n- **1954** -- George Devol izumi prvega industrijskega robota Unimate.\n- **1966** -- Shakey, prvi mobilni robot z AI, razume enostavne ukaze.\n- **1997** -- Robot Sojourner pristane na Marsu.\n\n### 21. stoletje\n\n- **2000** -- Honda predstavi ASIMO, humanoidnega robota.\n- **2011** -- IBM Watson zmaga v televizijskem kvizu Jeopardy.\n- **2020+** -- AI roboti se učijo hoditi, govoriti in pomagati ljudem.\n\n---\n\n## Slovenci in robotika\n\nAli si vedel, da ima Slovenija odlične inženirje robotike? Na Univerzi v Ljubljani in Mariboru razvijajo napredne robote za industrijo in medicino.\n\n---\n\n## Aktivnost\n\nUstvari časovnico robotike z najmanj 5 mejniki. Kateri izum se ti zdi najpomembnejši in zakaj?',
    updated_at = NOW()
WHERE title = 'Zgodovina robotike'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 1, Lesson 2: Vrste robotov
UPDATE course_lessons
SET content = E'# Vrste robotov\n\nRoboti prihajajo v vseh oblikah in velikostih. Spoznajmo glavne kategorije.\n\n---\n\n## 1. Industrijski roboti\n\nTo so veliki robotski kraki v tovarnah. Opravljajo ponavljajoče naloge: varjenje, barvanje, sestavljanje.\n\n- **Prednost:** hitri, natančni, ne potrebujejo počitka.\n- **Primer:** ABB, KUKA roboti.\n\n---\n\n## 2. Mobilni roboti\n\nRoboti, ki se premikajo po prostoru.\n\n- **Na kolesih:** dostavni roboti, Roomba.\n- **Na nogah:** Boston Dynamics Spot (pes), Atlas (humanoid).\n- **Leteči:** droni za dostavo in fotografijo.\n\n---\n\n## 3. Humanoidni roboti\n\nRoboti v obliki človeka. Imajo glavo, trup, roke in noge.\n\n- **Primer:** Tesla Optimus, Sophia.\n- **Izziv:** človekova hoja je izjemno težka za kopiranje!\n\n---\n\n## 4. Sodelovalni roboti (coboti)\n\nManjši roboti, ki varno delajo skupaj z ljudmi.\n\n- Uporabljajo se v majhnih delavnicah.\n- Imajo senzorje, da se ustavijo, če zaznajo človeka.\n\n---\n\n## 5. Mikro in nano roboti\n\nDrobceni roboti za medicino -- nekoč bodo potovali po našem telesu in popravljali celice!\n\n---\n\n## Naloga\n\nIzberi eno vrsto robota in napiši kratek esej (5--10 stavkov) o tem, kako bi ta robot lahko pomagal v tvoji šoli.',
    updated_at = NOW()
WHERE title = 'Vrste robotov'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 1, Lesson 3: Robotika v Sloveniji
UPDATE course_lessons
SET content = E'# Robotika v Sloveniji\n\nSlovenija je majhna država z velikimi dosežki v robotiki!\n\n---\n\n## Univerza v Ljubljani\n\nFakulteta za elektrotehniko ima enega najmodernejših laboratorijev za robotiko v regiji. Razvijajo:\n\n- **Humanoidne robote** za pomoč starejšim.\n- **Industrijske robote** za slovenska podjetja.\n- **Medicinske robote** za rehabilitacijo.\n\n---\n\n## Slovenska podjetja\n\n### RoboticsX\n\nRazvija napredne algoritme za robotsko manipulacijo.\n\n### Yaskawa Slovenija\n\nV Kočevju proizvajajo industrijske robote za ves svet.\n\n---\n\n## RoboLiga\n\nAli si vedel, da imamo v Sloveniji tekmovanja v robotiki za mlade? **RoboLiga** organizira tekmovanja, kjer ekipe učencev gradijo in programirajo robote za različne naloge.\n\n---\n\n## Zakaj je robotika pomembna za Slovenijo?\n\n- Slovenija ima močno industrijo, ki potrebuje avtomatizacijo.\n- Mladi inženirji robotike imajo odlične zaposlitvene možnosti.\n- Robotika združuje znanje matematike, fizike, informatike in inženirstva.\n\n---\n\n## Projekt\n\nRazišči, ali v tvoji okolici obstaja robotski krožek ali tekmovanje. Napiši načrt, kako bi se pridružil ali ustanovil svojega.',
    updated_at = NOW()
WHERE title = 'Robotika v Sloveniji'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 1, Lesson 4: Moj prvi virtualni robot
UPDATE course_lessons
SET content = E'# Moj prvi virtualni robot\n\nPreden gradimo fizičnega robota, se naučimo osnov z virtualnim!\n\n---\n\n## Simulatorji robotov\n\nSimulator je program, ki posnema resničnega robota v virtualnem svetu. To je kot videoigra, le da se učiš resničnih konceptov.\n\n### Prednosti simulatorjev:\n\n- **Brezplačni** -- ne potrebuješ dragih delov.\n- **Varni** -- ne moreš ničesar zlomiti.\n- **Hitri** -- poskuse ponoviš v sekundah.\n\n---\n\n## Osnovni ukazi za robota\n\nVsak robot razume osnovne ukaze:\n\n```\nPREMIKNI_NAPREJ(koraki)\nZAVRTI_LEVO(stopinje)\nZAVRTI_DESNO(stopinje)\nPOBERI(predmet)\nODLOŽI(predmet)\nČAKAJ(sekunde)\n```\n\n---\n\n## Primer programa\n\nNaš robot mora pobrati žogo in jo odnesti na cilj:\n\n```\nPREMIKNI_NAPREJ(3)\nZAVRTI_LEVO(90)\nPREMIKNI_NAPREJ(2)\nPOBERI(žoga)\nZAVRTI_DESNO(180)\nPREMIKNI_NAPREJ(5)\nODLOŽI(žoga)\n```\n\n---\n\n## Tvoja naloga\n\nNapiši program za naslednji scenarij:\n\n1. Robot stoji na začetku labirinta.\n2. Mora najti pot do izhoda.\n3. Na poti mora pobrati 2 zvezdici.\n\nNariši labirint in zapiši ukaze!',
    updated_at = NOW()
WHERE title = 'Moj prvi virtualni robot'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 2, Lesson 0: Kako robot vidi svet
UPDATE course_lessons
SET content = E'# Kako robot vidi svet\n\nMi vidimo svet skozi oči. Robot "vidi" skozi **senzorje** -- naprave, ki merijo različne lastnosti okolja.\n\n---\n\n## Vrste senzorjev\n\n### Kamere (vid)\n\nKamere zajamejo slike, ki jih robot analizira z AI.\n\n- **RGB kamere** -- vidijo barve kot mi.\n- **Globinske kamere** -- merijo razdaljo do objektov.\n- **Infrardeče kamere** -- vidijo v temi.\n\n### Ultrazvočni senzorji (sluh)\n\nDelujejo kot netopirji -- pošljejo zvočni val in merijo, kdaj se vrne.\n\n- Uporabljajo se za merjenje razdalje.\n- Roomba jih uporablja za zaznavanje sten.\n\n### Senzorji dotika\n\nRobot čuti pritisk, temperaturo in teksturo.\n\n- **Pritiskovni senzorji** -- ali je robot trčil v steno?\n- **Temperaturni senzorji** -- ali je predmet vroč?\n- **Silomer** -- kako močno robot drži predmet?\n\n### Žiroskop in pospeškometer\n\nMerita nagib in pospešek robota -- tako kot v tvojem telefonu!\n\n---\n\n## Eksperiment\n\nVzemi telefon in odpri aplikacijo, ki prikazuje senzorske podatke (npr. Phyphox). Koliko senzorjev ima tvoj telefon? Katere bi lahko nadomestili senzorje robota?',
    updated_at = NOW()
WHERE title = 'Kako robot vidi svet'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 2, Lesson 1: Računalniški vid
UPDATE course_lessons
SET content = E'# Računalniški vid\n\nRačunalniški vid je veja AI, ki uči računalnike **razumeti slike**.\n\n---\n\n## Kako robot "vidi" sliko?\n\nZa nas je slika mačke očitna. Za robota je slika le mreža številk -- vsak piksel ima vrednost za rdečo, zeleno in modro barvo.\n\n```\nSlika 3x3:\n[255,0,0]  [255,0,0]  [0,255,0]\n[255,0,0]  [0,0,0]    [0,255,0]\n[0,0,255]  [0,0,255]  [0,0,255]\n```\n\n---\n\n## Koraki računalniškega vida\n\n### 1. Zajem slike\n\nKamera zajame sliko in jo pretvori v številke.\n\n### 2. Obdelava\n\n- **Filtriranje** -- odstranjevanje šuma.\n- **Robovi** -- iskanje mej med objekti.\n- **Barve** -- ločevanje po barvah.\n\n### 3. Prepoznavanje\n\nAI model analizira obdelano sliko in prepozna objekte.\n\n- "To je mačka z 95-odstotno verjetnostjo."\n- "Na sliki sta 2 osebi in 1 pes."\n\n---\n\n## Uporaba v robotiki\n\n- **Samovozeči avtomobili** -- prepoznavanje prometnih znakov.\n- **Industrijski roboti** -- kontrola kakovosti.\n- **Droni** -- sledenje objektom.\n\n---\n\n## Aktivnost\n\nVzemi 5 slik različnih predmetov. Kakšne značilnosti bi robot moral prepoznati, da bi jih ločil? Naredi tabelo značilnosti za vsak predmet.',
    updated_at = NOW()
WHERE title = 'Računalniški vid'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 2, Lesson 2: Senzorji za navigacijo
UPDATE course_lessons
SET content = E'# Senzorji za navigacijo\n\nKako robot ve, kje je in kam mora iti?\n\n---\n\n## GPS -- Globalni pozicijski sistem\n\n- Deluje s pomočjo satelitov v orbiti.\n- Natančnost: 2--5 metrov na prostem.\n- **Problem:** ne deluje v zaprtih prostorih!\n\n---\n\n## LIDAR -- Lasersko merjenje razdalje\n\nLIDAR je kot 3D-skener okolja:\n\n1. Pošlje laserski žarek.\n2. Meri čas, da se žarek vrne.\n3. Ustvari 3D-zemljevid okolja.\n\nSamovozeči avtomobili uporabljajo LIDAR za "videnje" ceste.\n\n---\n\n## SLAM -- Simultano lociranje in kartiranje\n\nSLAM je tehnika, s katero robot **hkrati** ugotavlja, kje je, in gradi zemljevid okolja.\n\nPredstavljaj si, da te nekdo pusti v temen labirint:\n\n1. Tipaš stene okrog sebe.\n2. Zapomniš si, kje si že bil.\n3. Postopoma gradiš zemljevid v glavi.\n\nTo je SLAM za robote!\n\n---\n\n## Senzor odometrije\n\nMeri, koliko so se kolesa zavrtela. Iz tega izračuna, kako daleč je robot šel.\n\n- **Problem:** napake se kopičijo! Kolesa drsijo.\n\n---\n\n## Naloga\n\nNačrtuj navigacijski sistem za robota, ki dostavlja pakete v tvojem mestu. Katere senzorje bi uporabil? Nariši shemo.',
    updated_at = NOW()
WHERE title = 'Senzorji za navigacijo'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 2, Lesson 3: Zbiranje in analiza podatkov
UPDATE course_lessons
SET content = E'# Zbiranje in analiza podatkov\n\nSenzorji zbirajo ogromne količine podatkov. Kako jih robot razume?\n\n---\n\n## Vrste podatkov\n\n### Številčni podatki\n\n- Temperatura: 23,5 °C\n- Razdalja: 1,82 m\n- Hitrost: 0,5 m/s\n\n### Slikovni podatki\n\n- Slike iz kamere (milijone pikslov).\n- Video posnetki (30 slik na sekundo!).\n\n### Zvočni podatki\n\n- Glasovni ukazi.\n- Zvoki okolja.\n\n---\n\n## Filtriranje šuma\n\nSenzorji niso popolni -- včasih dajo napačne podatke (šum).\n\n**Primer:** temperaturni senzor v eni sekundi:\n\n```\n23.5, 23.6, 99.1, 23.4, 23.5\n```\n\nVrednost 99,1 je očitno napaka! Robot mora znati filtrirati šum.\n\n### Tehnike filtriranja:\n\n- **Povprečenje** -- vzameš povprečje zadnjih N meritev.\n- **Mediana** -- vzameš srednjo vrednost (ignorira ekstreme).\n- **Kalmanov filter** -- napredna tehnika, ki upošteva fizikalne zakone.\n\n---\n\n## Fuzija senzorjev\n\nKombiniranje podatkov iz več senzorjev za boljšo sliko:\n\n- GPS + odometrija = boljša lokacija.\n- Kamera + LIDAR = boljše zaznavanje objektov.\n\n---\n\n## Naloga\n\nPridobi 10 meritev temperature v svoji sobi (vsako minuto). Izračunaj povprečje in mediano. Ali se razlikujeta? Zakaj?',
    updated_at = NOW()
WHERE title = 'Zbiranje in analiza podatkov'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 2, Lesson 4: Projekt: Senzorska mreža
UPDATE course_lessons
SET content = E'# Projekt: Senzorska mreža\n\nV tem projektu boš načrtoval senzorsko mrežo za pameten dom.\n\n---\n\n## Scenarij\n\nTvoja družina želi pameten dom. Načrtuj sistem, ki:\n\n- Meri temperaturo in vlažnost v vsaki sobi.\n- Zaznava gibanje (varnost).\n- Nadzoruje porabo električne energije.\n- Opozori, če nekdo pozabi zapreti okno, ko pada dež.\n\n---\n\n## Korak 1: Načrt senzorjev\n\nZa vsako sobo določi:\n\n| Soba | Senzorji | Zakaj |\n|------|----------|-------|\n| Dnevna soba | Temp., gibanje, svetloba | Udobje, varnost |\n| Kuhinja | Temp., dim, plin | Varnost |\n| Spalnica | Temp., svetloba, zvok | Udobje, spanje |\n\n---\n\n## Korak 2: Povezovanje\n\nKako bodo senzorji komunicirali?\n\n- **WiFi** -- za senzorje blizu usmerjevalnika.\n- **Bluetooth** -- za bližnje naprave.\n- **Zigbee** -- za senzorje z majhno porabo.\n\n---\n\n## Korak 3: Pravila\n\nNapiši pravila za svoj pametni dom:\n\n```\nČE temperatura > 25 °C IN okno = zaprto\n  POTEM pošlji obvestilo "Odpri okno!"\n\nČE gibanje = zaznano IN čas > 23:00 IN nihče_doma = true\n  POTEM vklopi alarm\n```\n\n---\n\n## Korak 4: Vizualizacija\n\nNariši tloris doma in označi, kje bi postavil katere senzorje. Dodaj legendo z barvami za vsako vrsto senzorja.\n\n---\n\n## Bonus\n\nKateri podatki bi lahko izboljšali delovanje tvojega sistema, če bi dodal AI? Na primer: AI se nauči, kdaj se družina vrne domov, in vnaprej uravna temperaturo.',
    updated_at = NOW()
WHERE title = 'Projekt: Senzorska mreža'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 3, Lesson 0: Strojno učenje za robote
UPDATE course_lessons
SET content = E'# Strojno učenje za robote\n\nNamesto da robotu povemo vsako pravilo, ga lahko **naučimo** iz izkušenj.\n\n---\n\n## Tradicionalno programiranje proti strojnemu učenju\n\n**Tradicionalno:**\n\n```\nČE ovira_pred_teboj POTEM zavij_levo\nČE pot_prosta POTEM pojdi_naprej\n```\n\nProblem: ne moreš predvideti vsake situacije!\n\n**Strojno učenje:**\n\n```\nPokaži robotu 10.000 primerov:\n- Slika ceste → pravilna akcija\nRobot se sam nauči pravil!\n```\n\n---\n\n## Vrste strojnega učenja\n\n### Nadzorovano učenje\n\nRobotu pokažeš primere s pravilnimi odgovori.\n\n- "Ta slika = mačka, ta slika = pes."\n- Robot se nauči razlikovati.\n\n### Nenadzorovano učenje\n\nRobot sam najde vzorce v podatkih.\n\n- "Razvrsti te predmete v skupine."\n- Robot ugotovi, da so nekateri predmeti podobni.\n\n### Spodbujevano učenje (Reinforcement Learning)\n\nRobot se uči s poskušanjem:\n\n1. Poskusi akcijo.\n2. Dobi nagrado (dobro) ali kazen (slabo).\n3. Sčasoma se nauči najboljše strategije.\n\nTo je kot učenje vožnje s kolesom -- padeš, vstaneš, poskusiš znova!\n\n---\n\n## Primer\n\nRobot se uči hoditi:\n\n- Nagrada: korak naprej = +1 točka.\n- Kazen: padec = -10 točk.\n- Po 1000 poskusih se nauči hoditi!\n\n---\n\n## Razmisli\n\nKatero vrsto učenja bi uporabil za robota, ki:\n\n1. Sortira smeti? (nadzorovano)\n2. Igra šah? (spodbujevano)\n3. Organizira skladišče? (nenadzorovano)',
    updated_at = NOW()
WHERE title = 'Strojno učenje za robote'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 3, Lesson 1: Nevronske mreže
UPDATE course_lessons
SET content = E'# Nevronske mreže\n\nNevronske mreže so navdihnjene z delovanjem človeških **možganov**.\n\n---\n\n## Kako delujejo možgani?\n\nMožgani imajo ~86 milijard nevronov (živčnih celic).\n\n- Vsak nevron sprejme signale od drugih nevronov.\n- Če je signal dovolj močan, pošlje svoj signal naprej.\n- Povezave med nevroni se krepijo z vajo.\n\n---\n\n## Umetne nevronske mreže\n\nUmetna nevronska mreža posnema ta princip:\n\n```\nVhod → [Nevron 1] → [Nevron 2] → [Nevron 3] → Izhod\n         ↕              ↕              ↕\n       [Nevron 4] → [Nevron 5] → [Nevron 6]\n```\n\n### Plasti:\n\n1. **Vhodna plast** -- sprejme podatke (sliko, besedilo ...).\n2. **Skrite plasti** -- procesirajo podatke, iščejo vzorce.\n3. **Izhodna plast** -- dá končni odgovor.\n\n---\n\n## Učenje nevronske mreže\n\n1. Mreža dobi vhodni podatek.\n2. Izračuna odgovor.\n3. Primerja s pravilnim odgovorom.\n4. Popravi povezave (uteži) -- to je "učenje"!\n5. Ponovi 1000-krat.\n\n---\n\n## Globoko učenje (Deep Learning)\n\nKo ima mreža veliko skritih plasti, govorimo o **globokem učenju**. To je tehnologija za:\n\n- Prepoznavanje obrazov.\n- Samovozeče avtomobile.\n- ChatGPT in podobne modele.\n\n---\n\n## Aktivnost\n\nS tremi prijatelji simulirajte nevronsko mrežo: eden je vhod, dva sta skrita plast, eden je izhod. Pošiljajte si številke in opazujte, kako se "odgovor" spreminja.',
    updated_at = NOW()
WHERE title = 'Nevronske mreže'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 3, Lesson 2: Načrtovanje poti
UPDATE course_lessons
SET content = E'# Načrtovanje poti\n\nKako robot najde najboljšo pot od točke A do točke B?\n\n---\n\n## Problem\n\nRobot mora:\n\n- Priti od starta do cilja.\n- Se izogniti oviram.\n- Najti **najkrajšo** ali **najhitrejšo** pot.\n\n---\n\n## Algoritem A* (A-zvezdica)\n\nNajbolj priljubljen algoritem za načrtovanje poti.\n\n### Kako deluje:\n\n1. Začni na startnem polju.\n2. Poglej vsa sosednja polja.\n3. Za vsako polje izračunaj:\n   - g = razdalja od starta\n   - h = ocenjena razdalja do cilja\n   - f = g + h\n4. Premakni se na polje z najnižjim f.\n5. Ponavljaj, dokler ne prideš do cilja.\n\n### Primer na mreži:\n\n```\nS . . . .\n. X X . .\n. . X . .\n. . . . C\n\nS = start, C = cilj, X = ovira\n```\n\nRobot ne gre skozi X-polja, ampak jih obide.\n\n---\n\n## Dijkstrov algoritem\n\nPodobno kot A*, ampak brez ocene h.\n\n- Bolj počasen, toda vedno najde optimalno pot.\n\n---\n\n## Roboti v resničnem svetu\n\n- **Amazon skladišča:** tisoči robotov se premikajo med policami.\n- **Samovozeči avti:** načrtujejo pot skozi promet v realnem času.\n\n---\n\n## Naloga\n\nNa mrežastem papirju (10x10) nariši labirint. Nato ročno izvedi algoritem A*, da najdeš pot. Zapiši korake!',
    updated_at = NOW()
WHERE title = 'Načrtovanje poti'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 3, Lesson 3: Odločanje robota
UPDATE course_lessons
SET content = E'# Odločanje robota\n\nKako se robot odloči, kaj narediti?\n\n---\n\n## Odločitvena drevesa\n\nNajenostavnejši način za odločanje:\n\n```\nAli je pred mano ovira?\n├── DA → Ali je levo prosto?\n│   ├── DA → Zavij levo\n│   └── NE → Zavij desno\n└── NE → Pojdi naprej\n```\n\n---\n\n## Končni avtomati (State Machines)\n\nRobot je vedno v enem od **stanj** in prehaja med njimi:\n\n```\n[RAZISKUJ] --najdi predmet--> [POBERI]\n[POBERI] --uspeh--> [ODNESI]\n[POBERI] --neuspeh--> [RAZISKUJ]\n[ODNESI] --cilj dosežen--> [RAZISKUJ]\n```\n\nTo je kot igra, kjer ima lik različne "načine" (hoja, tek, boj).\n\n---\n\n## Verjetnostno odločanje\n\nVčasih robot ni 100 % prepričan:\n\n- "80 % verjetnost, da je to mačka."\n- "20 % verjetnost, da je to pes."\n\nRobot izračuna **pričakovano vrednost** vsake akcije:\n\n- Akcija A: 80 % x 10 točk = 8 točk.\n- Akcija B: 50 % x 20 točk = 10 točk.\n- Izbere B, ker ima višjo pričakovano vrednost!\n\n---\n\n## Večagentno odločanje\n\nKo več robotov dela skupaj, se morajo usklajevati:\n\n- Kdo gre kam?\n- Kako se izognejo trkom?\n- Kako si razdelijo naloge?\n\n---\n\n## Naloga\n\nNariši odločitveno drevo za robota, ki dostavlja pice. Upoštevaj: vreme, promet, pravilnost naslova, stanje pice.',
    updated_at = NOW()
WHERE title = 'Odločanje robota'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 3, Lesson 4: Projekt: AI agent v igri
UPDATE course_lessons
SET content = E'# Projekt: AI agent v igri\n\nZgradimo AI agenta, ki igra enostavno igro!\n\n---\n\n## Igra: Robot zbira diamante\n\nPravila:\n\n- Robot je na mreži 5x5.\n- Na mreži so 3 diamanti in 2 pasti.\n- Robot mora pobrati vse diamante in se izogniti pastim.\n- Za vsak diamant dobi +10 točk, za past -20 točk.\n\n---\n\n## Načrtovanje AI agenta\n\n### Strategija 1: Naključno\n\n```\nVsak korak: izberi naključno smer.\nEnostavnost: preprosto.\nUčinkovitost: slaba.\n```\n\n### Strategija 2: Požrešna (Greedy)\n\n```\nVsak korak: pojdi proti najbližjemu diamantu.\nIzogni se pastim, ki so na poti.\nEnostavnost: srednja.\nUčinkovitost: dobra.\n```\n\n### Strategija 3: Načrtovana\n\n```\n1. Najdi vse diamante.\n2. Izračunaj najkrajšo pot, ki obišče vse.\n3. Izogni se vsem pastim.\nEnostavnost: težka.\nUčinkovitost: odlična.\n```\n\n---\n\n## Tvoja naloga\n\n1. Na papirju nariši mrežo 5x5.\n2. Postavi 3 diamante (D) in 2 pasti (P).\n3. Postavi robota na začetno polje.\n4. Izvedi vse 3 strategije ročno.\n5. Za vsako strategijo zapiši:\n   - Koliko korakov je potreboval robot?\n   - Koliko točk je dosegel?\n   - Ali je padel v past?\n\n---\n\n## Bonus\n\nDodaj novo pravilo: robot ima le 15 korakov. Katera strategija zdaj zmaga? Zakaj?',
    updated_at = NOW()
WHERE title = 'Projekt: AI agent v igri'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 4, Lesson 0: Kaj pomeni avtonomnost?
UPDATE course_lessons
SET content = E'# Kaj pomeni avtonomnost?\n\n**Avtonomni robot** je robot, ki deluje sam, brez človeškega nadzora.\n\n---\n\n## Stopnje avtonomnosti\n\n### Stopnja 1: Daljinsko vodenje\n\nČlovek nadzoruje vsako gibanje robota.\n\n- Primer: dron s kontrolerjem.\n- Robot sam ne sprejema odločitev.\n\n### Stopnja 2: Polavtonomnost\n\nRobot izvaja naloge sam, človek nadzoruje.\n\n- Primer: tempomat v avtu.\n- Robot sledi pravilom, človek prevzame v nujnih primerih.\n\n### Stopnja 3: Pogojna avtonomnost\n\nRobot sam vozi v določenih razmerah.\n\n- Primer: Tesla Autopilot na avtocesti.\n- Človek mora biti pripravljen prevzeti.\n\n### Stopnja 4: Visoka avtonomnost\n\nRobot sam obvladuje skoraj vse situacije.\n\n- Primer: Waymo taxi v določenih mestih.\n- Človek ni potreben, toda robot deluje le v znanih okoljih.\n\n### Stopnja 5: Polna avtonomnost\n\nRobot sam deluje v vseh situacijah.\n\n- To za avtomobile še ne obstaja!\n- Morda v prihodnosti?\n\n---\n\n## Ključni izzivi avtonomnosti\n\n1. **Zaznavanje** -- robot mora razumeti okolje.\n2. **Načrtovanje** -- robot mora imeti cilj in pot.\n3. **Izvedba** -- robot mora natančno izvesti načrt.\n4. **Prilagajanje** -- robot mora reagirati na nepričakovano.\n\n---\n\n## Razmisli\n\nNa kateri stopnji avtonomnosti je:\n\n- Roomba sesalnik?\n- Mars rover?\n- Industrijski robotski krak?',
    updated_at = NOW()
WHERE title = 'Kaj pomeni avtonomnost?'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 4, Lesson 1: Samovozeči avtomobili
UPDATE course_lessons
SET content = E'# Samovozeči avtomobili\n\nSamovozeči avtomobili so eden najvidnejših primerov avtonomnih robotov.\n\n---\n\n## Kako delujejo?\n\n### Senzorji\n\n- **8+ kamer** -- 360-stopinjski pogled.\n- **LIDAR** -- 3D-zemljevid okolice.\n- **Radar** -- zaznava objektov v slabem vremenu.\n- **Ultrazvok** -- bližnji objekti pri parkiranju.\n\n### AI možgani\n\n1. Senzorji zajamejo podatke.\n2. AI prepozna: cesto, avtomobile, pešce, znake.\n3. AI načrtuje pot in hitrost.\n4. Izvede vožnjo skozi aktuatorje (volan, plin, zavore).\n\nVse to se zgodi **30-krat na sekundo**!\n\n---\n\n## Ključni igralci\n\n| Podjetje | Pristop | Status |\n|----------|---------|--------|\n| Waymo (Google) | LIDAR + kamere | Taxi v Phoenixu, SF |\n| Tesla | Samo kamere | Autopilot, FSD beta |\n| Cruise (GM) | LIDAR + kamere | Začasno ustavljeno |\n| Baidu Apollo | LIDAR + kamere | Taxi na Kitajskem |\n\n---\n\n## Etične dileme\n\nSamovozeči avto mora sprejemati težke odločitve:\n\n- Zavij levo (udari steno) ali desno (udari drevo)?\n- Zaustavi se nenadoma (potnike trese) ali nadaljuje?\n\nTo so vprašanja, ki jih morajo rešiti inženirji IN etiki skupaj.\n\n---\n\n## Aktivnost\n\nOblikuj mesto s petimi ulicami na papirju. Nariši pot samovozečega avtomobila in označi vse, kar mora zaznati (znake, pešce, luči, ovire).',
    updated_at = NOW()
WHERE title = 'Samovozeči avtomobili'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 4, Lesson 2: Roboti v vesolju
UPDATE course_lessons
SET content = E'# Roboti v vesolju\n\nVesolje je nevarno za ljudi, toda odlično za robote!\n\n---\n\n## Mars roverji\n\n### Curiosity (2012--danes)\n\n- Velikost avtomobila.\n- Jedrski vir energije.\n- Raziskuje površje Marsa, analizira kamenje.\n- Komunikacija z Zemljo traja 4--24 minut!\n\n### Perseverance (2021--danes)\n\n- Išče znake preteklega življenja.\n- S seboj je pripeljal **Ingenuity** -- prvi helikopter na drugem planetu!\n- Zbira vzorce za kasnejši transport na Zemljo.\n\n---\n\n## Zakaj roboti in ne ljudje?\n\n1. **Sevanje** -- vesolje je polno smrtonosnega sevanja.\n2. **Zrak** -- ni kisika za dihanje.\n3. **Čas** -- potovanje do Marsa traja 7 mesecev.\n4. **Stroški** -- robot je 100-krat cenejši od človeške misije.\n\n---\n\n## Izziv: Zakasnitev komunikacije\n\nSignal od Zemlje do Marsa potuje 4--24 minut.\n\n- Ne moreš "voziti" roverja v realnem času.\n- Rover mora biti delno **avtonomen** -- sam se izogiba nevarnostim.\n- Ukaze pošljemo enkrat na dan, rover jih izvede sam.\n\n---\n\n## Prihodnost\n\n- **Robotski gradbeniki** -- bodo gradili baze na Luni in Marsu pred prihodom ljudi.\n- **Robotski rudarji** -- bodo kopali minerale na asteroidih.\n- **Vesoljski teleskopi** -- robotski sistemi, ki sami popravljajo napake.\n\n---\n\n## Naloga\n\nNačrtuj robota za raziskovanje Jupitrovega meseca Evrope (pokrit z ledom, pod njim ocean). Kakšne senzorje in sposobnosti bi potreboval?',
    updated_at = NOW()
WHERE title = 'Roboti v vesolju'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 4, Lesson 3: Roji robotov (Swarm Robotics)
UPDATE course_lessons
SET content = E'# Roji robotov (Swarm Robotics)\n\nNamesto enega velikega robota -- tisoč majhnih, ki delajo skupaj!\n\n---\n\n## Navdih iz narave\n\n### Mravlje\n\n- Posamezna mravljica je preprosta.\n- Skupaj gradijo kompleksne kolonije.\n- Komunicirajo s feromoni (kemičnimi sledmi).\n\n### Čebele\n\n- Izvidnice najdejo cvetlice.\n- S plesom povedo drugim, kje je hrana.\n- Skupaj se odločijo za najboljši vir.\n\n### Ribe\n\n- Plavanje v jati za zaščito pred plenilci.\n- Nobena riba ni "vodja" -- vse sledijo enostavnim pravilom.\n\n---\n\n## Pravila za roj robotov\n\nVsak robot sledi trem enostavnim pravilom:\n\n1. **Separacija** -- ne pridi preblizu drugim.\n2. **Poravnava** -- premikaj se v isti smeri kot sosedje.\n3. **Kohezija** -- ostani blizu skupine.\n\nIz teh treh pravil nastane kompleksno skupinsko vedenje!\n\n---\n\n## Uporabe\n\n### Iskanje in reševanje\n\n- 100 majhnih dronov preišče ruševine po potresu.\n- Vsak pregleda majhno območje.\n- Ko eden najde osebo, pokliče ostale.\n\n### Kmetijstvo\n\n- Roji majhnih robotov sadijo, škropijo, žanjejo.\n- Vsak robot skrbi za svoj del polja.\n\n### Gradbeništvo\n\n- Majhni roboti skupaj gradijo strukture.\n- Kot termiti, ki gradijo termitnjake.\n\n---\n\n## Aktivnost\n\nZ razredom simulirajte roj: vsak učenec je "robot" in sledi trem pravilom. Opazujte, kaj se zgodi po 5 minutah premikanja po dvorani!',
    updated_at = NOW()
WHERE title = 'Roji robotov (Swarm Robotics)'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 4, Lesson 4: Projekt: Načrtuj avtonomno misijo
UPDATE course_lessons
SET content = E'# Projekt: Načrtuj avtonomno misijo\n\nČas je za velik projekt! Načrtuj celotno avtonomno robotsko misijo.\n\n---\n\n## Izberi scenarij\n\nIzberi ENEGA:\n\n### A) Podvodna raziskava\n\nRobot raziskuje morsko dno pri Piranu.\n\n- Kartira morsko dno.\n- Fotografira morsko življenje.\n- Zbira vzorce vode.\n\n### B) Mestna dostava\n\nRobot dostavlja pakete po Ljubljani.\n\n- Navigira po pločnikih.\n- Se izogiba pešcem.\n- Najde pravi naslov.\n\n### C) Gozdni nadzor\n\nRobot patruljira po slovenskem gozdu.\n\n- Zaznava gozdne požare.\n- Spremlja divje živali.\n- Poroča o stanju dreves.\n\n---\n\n## Za vsak scenarij opiši:\n\n### 1. Senzorji (2--3 strani)\n\n- Katere senzorje bo imel robot?\n- Zakaj prav te?\n\n### 2. AI sistemi (2--3 strani)\n\n- Kako bo robot sprejemal odločitve?\n- Katero vrsto strojnega učenja bo uporabil?\n\n### 3. Navigacija (1--2 strani)\n\n- Kako bo robot vedel, kje je?\n- Kako bo načrtoval pot?\n\n### 4. Komunikacija (1 stran)\n\n- Kako bo robot poročal človeku?\n- Kaj, če izgubi signal?\n\n### 5. Varnost (1 stran)\n\n- Kaj, če se robot pokvari?\n- Kako zaščitimo okolje pred robotom?\n\n---\n\n## Oddaj\n\nNapiši poročilo (5--10 strani) z risbami in diagrami. Bonus: naredi predstavitev za razred!',
    updated_at = NOW()
WHERE title = 'Projekt: Načrtuj avtonomno misijo'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 5, Lesson 0: Inženirski proces
UPDATE course_lessons
SET content = E'# Inženirski proces\n\nPravi inženirji sledijo strukturiranemu procesu pri razvoju robotov.\n\n---\n\n## 5 korakov inženirskega procesa\n\n### 1. Definiraj problem\n\n- Kakšno nalogo mora robot opravljati?\n- Kdo bo robota uporabljal?\n- Kakšne so omejitve (velikost, cena, energija)?\n\n### 2. Raziskuj\n\n- Ali že obstajajo podobni roboti?\n- Kakšne tehnologije so na voljo?\n- Kaj pravi znanost o problemu?\n\n### 3. Načrtuj\n\n- Nariši načrte robota.\n- Izberi komponente (senzorje, motorje, procesor).\n- Načrtuj programsko opremo.\n- Izračunaj stroške.\n\n### 4. Zgradi in testiraj\n\n- Sestavi prototip.\n- Testiraj v nadzorovanem okolju.\n- Zapiši rezultate.\n- Popravi napake.\n\n### 5. Izboljšaj\n\n- Analiziraj testne rezultate.\n- Kaj deluje dobro? Kaj ne?\n- Naredi spremembe.\n- Testiraj znova!\n\n---\n\n## Iteracija\n\nInženirski proces ni linearen -- je **krožen**. Vedno se vračamo na prejšnje korake in izboljšujemo.\n\n```\nDefiniraj → Raziskuj → Načrtuj → Zgradi → Testiraj\n    ↑                                         ↓\n    ←←←←←←←← Izboljšaj ←←←←←←←←←←←\n```\n\n---\n\n## Naloga\n\nZa svoj končni projekt zapiši:\n\n1. Problem, ki ga rešuješ.\n2. 3 obstoječe rešitve (raziskava).\n3. Prednosti tvojega pristopa.',
    updated_at = NOW()
WHERE title = 'Inženirski proces'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 5, Lesson 1: Načrtovanje mojega robota
UPDATE course_lessons
SET content = E'# Načrtovanje mojega robota\n\nČas je za načrtovanje tvojega lastnega robota!\n\n---\n\n## Korak 1: Izberi nalogo\n\nTvoj robot mora rešiti **resnični problem**. Nekaj idej:\n\n- Robot, ki pomaga starim staršem prinesti stvari.\n- Robot, ki čisti smetnjak.\n- Robot, ki pomaga pri učenju matematike.\n- Robot, ki skrbi za vrt, ko si na počitnicah.\n\n---\n\n## Korak 2: Zahteve\n\nZa vsako nalogo zapiši zahteve:\n\n| Zahteva | Opis | Prioriteta |\n|---------|------|------------|\n| Velikost | Največ 50 cm x 50 cm | Visoka |\n| Teža | Največ 5 kg | Srednja |\n| Energija | Baterija za 2 uri | Visoka |\n| Hitrost | 0,5 m/s | Nizka |\n\n---\n\n## Korak 3: Skica\n\nNariši robota iz treh pogledov:\n\n- Spredaj.\n- S strani.\n- Od zgoraj.\n\nOznači vse dele:\n\n- Kje so senzorji?\n- Kje je procesor?\n- Kje so motorji/kolesa?\n- Kje je baterija?\n\n---\n\n## Korak 4: Seznam komponent\n\n```\n1x Arduino Mega (procesor)       -- 25 EUR\n2x DC motor z gumijastimi kolesi -- 8 EUR\n1x Ultrazvočni senzor HC-SR04    -- 3 EUR\n1x Modul kamere                  -- 15 EUR\n1x Li-Po baterija 7,4 V          -- 12 EUR\n1x Robotsko šasijo (3D-tisk)     -- 10 EUR\n─────────────────────────────────\nSKUPAJ:                            73 EUR\n```\n\n---\n\n## Naloga\n\nIzpolni vse 4 korake za TVOJEGA robota. Oddaj načrt z risbami in seznamom komponent.',
    updated_at = NOW()
WHERE title = 'Načrtovanje mojega robota'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 5, Lesson 2: Programiranje robota
UPDATE course_lessons
SET content = E'# Programiranje robota\n\nSedaj, ko imamo načrt, napišimo program za robota!\n\n---\n\n## Psevdokoda\n\nPreden pišemo pravi program, napišemo **psevdokodo** -- program v navadnem jeziku.\n\n### Primer: Robot čistilec\n\n```\nPROGRAM robot_čistilec:\n\n  PONAVLJAJ:\n    slika = zajemi_sliko()\n    smeti = najdi_smeti(slika)\n\n    ČE smeti.najdene:\n      pot = izračunaj_pot(moja_lokacija, smeti.lokacija)\n      premikaj_se(pot)\n      poberi(smeti)\n      pot_do_koša = izračunaj_pot(moja_lokacija, koš)\n      premikaj_se(pot_do_koša)\n      odloži(smeti)\n    SICER:\n      premikaj_se_naključno()\n\n    ČE baterija < 20 %:\n      pot_domov = izračunaj_pot(moja_lokacija, polnilnica)\n      premikaj_se(pot_domov)\n      polni_se()\n  KONEC_PONAVLJAJ\n```\n\n---\n\n## Moduli programa\n\nRazdeli program na module:\n\n### Modul zaznave\n\n- Bere podatke iz senzorjev.\n- Procesira slike.\n- Vrne informacije o okolju.\n\n### Modul načrtovanja\n\n- Sprejema odločitve.\n- Računa pot.\n- Upravlja z nalogami.\n\n### Modul gibanja\n\n- Nadzoruje motorje.\n- Upravlja s hitrostjo.\n- Izvaja zavoje.\n\n### Modul varnosti\n\n- Preverja baterijo.\n- Zaznava trke.\n- Zasilna ustavitev.\n\n---\n\n## Naloga\n\nNapiši psevdokodo za TVOJEGA robota. Razdeli jo na vsaj 3 module.',
    updated_at = NOW()
WHERE title = 'Programiranje robota'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 5, Lesson 3: Testiranje in odpravljanje napak
UPDATE course_lessons
SET content = E'# Testiranje in odpravljanje napak\n\nNoben robot ne deluje popolno od začetka. Testiranje je ključno!\n\n---\n\n## Vrste testov\n\n### Enotski testi\n\nTestiramo posamezne dele:\n\n- Ali motor pravilno zavrti kolesa?\n- Ali senzor pravilno meri razdaljo?\n- Ali kamera zajame sliko?\n\n### Integracijski testi\n\nTestiramo, kako deli delujejo skupaj:\n\n- Ali robot zavije, ko senzor zazna oviro?\n- Ali pobere predmet, ko ga kamera prepozna?\n\n### Sistemski testi\n\nTestiramo celotnega robota v resničnem okolju:\n\n- Ali robot opravi nalogo od začetka do konca?\n- Koliko časa potrebuje?\n- Ali se pravilno obnaša v nepričakovanih situacijah?\n\n---\n\n## Pogosti problemi\n\n### Mehanski problemi\n\n- Kolesa drsijo → dodaj gumijaste obroče.\n- Robot se prevrne → znižaj težišče.\n- Prijemalnik ne prime → prilagodi pritisk.\n\n### Programski problemi (hrošči)\n\n- Robot se vrti v krogu → preveri smer motorjev.\n- Robot se zaleti v steno → senzor ne deluje pravilno.\n- Robot se ustavi brez razloga → preveri baterijo.\n\n### AI problemi\n\n- Robot ne prepozna predmetov → potrebuje več učnih podatkov.\n- Robot se odloča prepočasi → optimiziraj algoritem.\n\n---\n\n## Dnevnik testiranja\n\n| Test | Pričakovano | Dejansko | Status | Popravek |\n|------|-------------|----------|--------|-----------|\n| Vožnja 1 m naravnost | 1,00 m | 0,95 m | OK | / |\n| Obrat 90° | 90° | 105° | NAPAKA | Zmanjšaj čas motorja |\n\n---\n\n## Naloga\n\nSestavi načrt testiranja za svojega robota: 5 enotskih, 3 integracijske in 2 sistemska testa.',
    updated_at = NOW()
WHERE title = 'Testiranje in odpravljanje napak'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');

-- Module 5, Lesson 4: Končni projekt: Predstavitev
UPDATE course_lessons
SET content = E'# Končni projekt: Predstavitev\n\nČestitke! Prišel si do konca tečaja! Čas je za končno predstavitev.\n\n---\n\n## Kaj moraš oddati\n\n### 1. Pisno poročilo (8--12 strani)\n\n**Uvod** (1 stran)\n\n- Kakšen problem rešuješ?\n- Zakaj je ta problem pomemben?\n\n**Načrt robota** (3--4 strani)\n\n- Skica robota z oznakami.\n- Seznam komponent s cenami.\n- Razlaga izbire vsakega dela.\n\n**AI in programiranje** (2--3 strani)\n\n- Psevdokoda programa.\n- Razlaga AI algoritmov, ki jih uporabljaš.\n- Kako se robot uči/odloča?\n\n**Testni načrt** (1--2 strani)\n\n- Tabela testov.\n- Pričakovani rezultati.\n- Kako bi popravil napake?\n\n**Zaključek** (1 stran)\n\n- Kaj si se naučil?\n- Kaj bi izboljšal, če bi imel več časa?\n- Kako vidiš prihodnost tvojega robota?\n\n---\n\n### 2. Predstavitev (5--10 minut)\n\n- Pripravi diapozitive (8--12).\n- Predstavi problem, rešitev in rezultate.\n- Odgovori na vprašanja publike.\n\n---\n\n### 3. Demo (neobvezno)\n\n- Če si zgradil prototip ali simulacijo, jo pokaži!\n- Tudi papirni model ali risba je odlična.\n\n---\n\n## Ocenjevanje\n\n| Kriterij | Točke |\n|----------|-------|\n| Kreativnost problema | 20 |\n| Kakovost načrta | 25 |\n| Uporaba AI konceptov | 25 |\n| Predstavitev | 20 |\n| Testni načrt | 10 |\n| **SKUPAJ** | **100** |\n\n---\n\n## Nasveti\n\n- Bodi navdušen nad svojim projektom!\n- Razloži kompleksne koncepte enostavno.\n- Uporabi slike in diagrame.\n- Vadi predstavitev pred ogledalom.\n\n**Srečno in zabavaj se! Robotika je prihodnost!**',
    updated_at = NOW()
WHERE title = 'Končni projekt: Predstavitev'
  AND course_id = (SELECT id FROM courses WHERE slug = 'robotics-and-ai');
