-- Update AI Safety & Ethics course content: fix grammar, improve readability
-- Course: ai-safety-ethics (8 lessons, 4 modules x 2)

-- Module 1, Lesson 0: Kaj so osebni podatki?
UPDATE course_lessons
SET content = E'# Kaj so osebni podatki?\n\n**Osebni podatki** so vse informacije, ki te identificirajo ali se nanašajo na te.\n\n---\n\n## Vrste osebnih podatkov\n\n### Očitni podatki\n\n- Ime in priimek.\n- Naslov.\n- Telefonska številka.\n- E-poštni naslov.\n- Fotografija obraza.\n\n### Manj očitni podatki\n\n- Lokacija tvojega telefona.\n- Kaj iščeš na internetu.\n- Katere videe gledaš.\n- S kom se pogovarjaš.\n- Kdaj se zbudiš in kdaj zaspiš.\n\n### Občutljivi podatki\n\n- Zdravstveni podatki.\n- Verska ali politična prepričanja.\n- Biometrični podatki (prstni odtis, obraz).\n\n---\n\n## Kako AI zbira tvoje podatke?\n\n### Pametni asistenti\n\nKo rečeš "Hey Siri" ali "OK Google", tvoj glas potuje na strežnike podjetja.\n\n- Ali veš, da se včasih posnetki shranijo?\n- Ljudje jih lahko poslušajo za "izboljšanje storitve."\n\n### Družabna omrežja\n\n- TikTok beleži, katere videe gledaš in koliko časa.\n- Instagram ve, kje si bil (geolokacija).\n- YouTube priporoča na podlagi VSEGA, kar si gledal.\n\n### Igre\n\n- Mnoge igre zbirajo podatke o tvojem vedenju.\n- Klepet v igrah se pogosto shranjuje.\n\n---\n\n## GDPR -- Tvoje pravice\n\nV EU (tudi v Sloveniji!) imaš pravice:\n\n1. **Pravica vedeti** -- kaj podjetje ve o tebi.\n2. **Pravica do izbrisa** -- zahtevaj, da izbrišejo tvoje podatke.\n3. **Pravica do popravka** -- popravi napačne podatke.\n4. **Pravica do prenosa** -- prenesi podatke drugam.\n\n---\n\n## Naloga\n\nPojdi v nastavitve svoje najljubše aplikacije na telefonu. Poišči "Zasebnost" ali "Privacy". Kaj vse lahko vidiš in spremeniš?',
    updated_at = NOW()
WHERE title = 'Kaj so osebni podatki?'
  AND course_id = (SELECT id FROM courses WHERE slug = 'ai-safety-ethics');

-- Module 1, Lesson 1: Kako zaščitim svojo zasebnost
UPDATE course_lessons
SET content = E'# Kako zaščitim svojo zasebnost\n\nSedaj, ko veš, kakšne podatke AI zbira, se naučimo, kako se zaščititi.\n\n---\n\n## 10 zlatih pravil digitalne zasebnosti\n\n### 1. Močna gesla\n\n- Dolga (12+ znakov).\n- Mešanica črk, številk, simbolov.\n- **Nikoli** isto geslo za več storitev.\n- Uporabi upravljalnik gesel!\n\n### 2. Dvostopenjska avtentikacija (2FA)\n\nPoleg gesla potrebuješ še kodo iz telefona.\n\n- Vklopi 2FA povsod, kjer je mogoče.\n- SMS je sprejemljiv, toda aplikacija (Google Authenticator) je boljša.\n\n### 3. Preveri dovoljenja aplikacij\n\n- Ali igra res potrebuje dostop do kamere?\n- Ali svetilka res potrebuje lokacijo?\n- Odstrani dovoljenja, ki niso potrebna.\n\n### 4. Bodi previden z javnim WiFi\n\n- Na javnem WiFi ne vnašaj gesel.\n- Uporabi VPN za zaščito.\n\n### 5. Razmisli, preden objaviš\n\n- Kar objaviš na internetu, ostane ZA VEDNO.\n- Ne deli lokacije v realnem času.\n- Ne objavljaj osebnih podatkov.\n\n### 6. Preveri nastavitve zasebnosti\n\n- Na vsakem družabnem omrežju prilagodi nastavitve.\n- Omeji, kdo vidi tvoje objave.\n\n### 7. Pazi na phishing\n\n- Ne klikaj na sumljive povezave.\n- Preveri e-poštni naslov pošiljatelja.\n- Nobeno podjetje te ne bo prosilo za geslo po e-pošti.\n\n### 8. Posodabljaj naprave\n\n- Posodobitve pogosto popravijo varnostne luknje.\n- Vklopi samodejne posodobitve.\n\n### 9. Preberi pogoje uporabe\n\n- Vsaj preleti, kaj podpisuješ.\n- Pazi na "delimo podatke s tretjimi stranmi."\n\n### 10. Pogovarjaj se s starši\n\n- Če nisi prepričan, vprašaj starše ali učitelja.\n- Skupaj preglejta nastavitve tvojih naprav.\n\n---\n\n## Aktivnost\n\nIzvedi "zasebnostni pregled" na svoji najljubši aplikaciji. Zapiši:\n\n1. Katera dovoljenja ima?\n2. Katere podatke zbira?\n3. Kaj si spremenil po pregledu?',
    updated_at = NOW()
WHERE title = 'Kako zaščitim svojo zasebnost'
  AND course_id = (SELECT id FROM courses WHERE slug = 'ai-safety-ethics');

-- Module 2, Lesson 0: Kaj je pristranskost v AI?
UPDATE course_lessons
SET content = E'# Kaj je pristranskost v AI?\n\nAI se uči iz podatkov. Če so podatki **pristranski**, bo tudi AI pristranska.\n\n---\n\n## Kaj pomeni pristranskost?\n\nPristranskost pomeni, da AI obravnava nekatere ljudi ali skupine nepošteno.\n\n---\n\n## Resnični primeri\n\n### Prepoznavanje obrazov\n\n- Raziskava MIT je pokazala, da AI za prepoznavanje obrazov naredi **34 % več napak** pri temnejših obrazih.\n- Zakaj? Ker so bili učni podatki večinoma svetli obrazi.\n\n### Zaposlovanje\n\n- Amazon je razvil AI za izbiro kandidatov.\n- AI je dajala prednost moškim, ker so bili v preteklosti večinoma moški zaposleni.\n- Amazon je sistem ukinil!\n\n### Zdravstvo\n\n- AI za diagnosticiranje kožnih bolezni deluje slabše na temnejši koži.\n- Ker so medicinski učbeniki vsebovali večinoma slike svetle kože.\n\n### Prevajanje\n\n- "The doctor" → "zdravnik" (moški).\n- "The nurse" → "medicinska sestra" (ženski).\n- AI predpostavlja spol na podlagi stereotipov!\n\n---\n\n## Zakaj se to dogaja?\n\n1. **Pristranski podatki** -- AI se uči iz preteklosti, ki ni bila vedno poštena.\n2. **Premalo raznolikosti** -- med razvijalci AI je premalo raznolikosti.\n3. **Nenamerno** -- nihče ne želi pristranskega AI, ampak se zgodi.\n\n---\n\n## Kako popraviti?\n\n- Raznolike učne podatke.\n- Testiranje na različnih skupinah.\n- Raznolike ekipe razvijalcev.\n- Redno preverjanje rezultatov.\n\n---\n\n## Razmisli\n\nAli si kdaj opazil, da ti algoritem priporoča vedno iste vrste vsebin? Zakaj misliš, da je tako?',
    updated_at = NOW()
WHERE title = 'Kaj je pristranskost v AI?'
  AND course_id = (SELECT id FROM courses WHERE slug = 'ai-safety-ethics');

-- Module 2, Lesson 1: Ustvarjajmo pošteno AI
UPDATE course_lessons
SET content = E'# Ustvarjajmo pošteno AI\n\nKako lahko zagotovimo, da je AI poštena do vseh?\n\n---\n\n## Načela poštene AI\n\n### 1. Transparentnost\n\n- Uporabniki morajo vedeti, da komunicirajo z AI.\n- AI mora razložiti svoje odločitve.\n- "Priporočam ti ta film, ker si gledal podobne filme."\n\n### 2. Pravičnost\n\n- AI mora obravnavati vse ljudi enako.\n- Redno testiranje na različnih skupinah.\n- Neodvisni pregledi algoritmov.\n\n### 3. Odgovornost\n\n- Nekdo mora biti odgovoren za odločitve AI.\n- Če AI naredi napako, mora nekdo odgovarjati.\n- Podjetja morajo prevzeti odgovornost.\n\n### 4. Vključevanje\n\n- Pri razvoju AI morajo sodelovati raznolike skupine.\n- Upoštevaj mnenje uporabnikov.\n- Testiraj z resničnimi ljudmi iz različnih ozadij.\n\n---\n\n## Praktične vaje\n\n### Vaja 1: Preveri pristranskost\n\nVzemi AI klepetalni robot (ChatGPT, Gemini) in ga vprašaj:\n\n- "Opiši zdravnika." -- Ali predpostavi spol?\n- "Opiši inženirja." -- Ali predpostavi spol ali raso?\n- "Opiši medicinsko sestro." -- Ali predpostavi spol?\n\n### Vaja 2: Popravi podatke\n\nImaš nabor slik za učenje AI prepoznavanja sadja:\n\n- 90 jabolk, 5 banan, 5 pomaranč.\n- Ali bo AI dobra pri prepoznavanju banan? NE!\n- Kako popraviš? Dodaj več slik banan in pomaranč!\n\n### Vaja 3: Napiši pravila\n\nPredstavljaj si, da razvijaš AI za šolske ocene.\nNapiši 5 pravil, ki zagotavljajo poštenost:\n\n1. AI ne sme vedeti imena ali spola učenca.\n2. AI ocenjuje le vsebino, ne oblike.\n3. ...\n\n---\n\n## Skupinski projekt\n\nV skupinah po 3--4 ustvarite "Listino poštene AI" -- dokument z 10 pravili, ki bi jih moral upoštevati vsak razvijalec AI. Predstavite jo razredu.',
    updated_at = NOW()
WHERE title = 'Ustvarjajmo pošteno AI'
  AND course_id = (SELECT id FROM courses WHERE slug = 'ai-safety-ethics');

-- Module 3, Lesson 0: AI in dezinformacije
UPDATE course_lessons
SET content = E'# AI in dezinformacije\n\nAI lahko ustvari zelo prepričljive lažne vsebine. Kako jih prepoznati?\n\n---\n\n## Deepfakes\n\nDeepfake je video ali slika, kjer AI zamenja obraz ali glas osebe.\n\n### Kako deluje?\n\n1. AI analizira 1000+ slik osebe.\n2. Nauči se, kako izgleda iz vseh kotov.\n3. Ustvari novo sliko/video s to osebo.\n\n### Nevarnosti:\n\n- Lažne novice s "posnetki" politikov.\n- Prevare z lažnimi glasovnimi klici.\n- Lažni profili na družabnih omrežjih.\n\n---\n\n## Kako prepoznati deepfake?\n\n### Vizualni znaki:\n\n- Nenaravno utripanje z očmi.\n- Zamegljeni robovi obraza.\n- Neskladnost med ustnicami in govorom.\n- Čudna svetloba ali sence.\n- Nesimetrični uhani ali očala.\n\n### Orodja za preverjanje:\n\n- **Obratno iskanje slik** (Google Images) -- ali slika obstaja drugje?\n- **Preveri vir** -- ali je novica iz zaupanja vrednega vira?\n- **Preveri datum** -- ali je vsebina res nova?\n\n---\n\n## AI-generirano besedilo\n\nChatGPT in podobni modeli lahko napišejo zelo prepričljivo besedilo.\n\n- Šolski eseji, ki jih ni napisal učenec.\n- Lažne ocene izdelkov.\n- Lažni komentarji na forumih.\n\n### Kako prepoznati?\n\n- Besedilo je "preveč popolno" -- brez napak, toda brez osebnosti.\n- Ponavljajoči vzorci in fraze.\n- Preveri dejstva -- AI pogosto "halucinira" (izmisli si dejstva).\n\n---\n\n## 5 korakov za preverjanje informacij\n\n1. **Kdo** to pravi? (vir)\n2. **Kaj** je dokaz? (dejstva)\n3. **Kdaj** je bilo objavljeno? (aktualnost)\n4. **Zakaj** to objavljajo? (motiv)\n5. **Kje** še piše o tem? (potrditev)\n\n---\n\n## Naloga\n\nPoišči 3 primere deepfake videov na internetu. Zapiši, kako si ugotovil, da so lažni.',
    updated_at = NOW()
WHERE title = 'AI in dezinformacije'
  AND course_id = (SELECT id FROM courses WHERE slug = 'ai-safety-ethics');

-- Module 3, Lesson 1: Varna uporaba AI orodij
UPDATE course_lessons
SET content = E'# Varna uporaba AI orodij\n\nAI orodja so lahko zelo koristna, toda uporabljati jih moramo odgovorno.\n\n---\n\n## Pravila za varno uporabo ChatGPT in podobnih\n\n### 1. Ne deli osebnih podatkov\n\n- NE: "Živim na Prešernovi 15 v Ljubljani."\n- DA: "Živim v mestu v Sloveniji."\n- Vse, kar napišeš, se shrani in uporabi za učenje.\n\n### 2. Preveri odgovore\n\n- AI se pogosto moti -- zlasti pri datumih, imenih, dejstvih.\n- Vedno preveri pomembne informacije v zanesljivem viru.\n- AI "halucinira" -- izmišljuje si stvari s prepričljivostjo.\n\n### 3. Ne kopiraj brez razumevanja\n\n- Če AI napiše šolski esej, ga NE oddaj kot svojega.\n- Uporabi AI kot **pomočnika** za učenje, ne kot nadomestilo.\n- Razloži učitelju, kako si uporabil AI.\n\n### 4. Starostne omejitve\n\n- ChatGPT: 13+ let (mlajši z dovoljenjem staršev).\n- DALL-E: 18+ let.\n- Različna orodja imajo različne omejitve.\n\n---\n\n## Varna uporaba AI za generiranje slik\n\n### Kaj smeš:\n\n- Ustvarjati umetnost za osebno uporabo.\n- Generirati slike za šolske projekte.\n- Eksperimentirati s slogi in idejami.\n\n### Česa NE smeš:\n\n- Ustvarjati slik resničnih oseb brez dovoljenja.\n- Generirati neprimerne vsebine.\n- Trditi, da si sliko narisal sam.\n\n---\n\n## AI in šolsko delo\n\n### Dovoljeno:\n\n- AI ti pomaga razumeti koncept.\n- AI ti dá ideje za projekt.\n- AI ti pomaga pri preverjanju slovnice.\n\n### Ni dovoljeno:\n\n- AI napiše tvoj esej.\n- AI reši tvojo domačo nalogo.\n- Oddaš AI delo kot svoje.\n\n---\n\n## Dogovor z družino\n\nS starši se dogovorite o pravilih za uporabo AI:\n\n1. Katera orodja smem uporabljati?\n2. Koliko časa na dan?\n3. Kaj naredim, če vidim nekaj neprimernega?\n4. Komu povem, če sem v dvomih?',
    updated_at = NOW()
WHERE title = 'Varna uporaba AI orodij'
  AND course_id = (SELECT id FROM courses WHERE slug = 'ai-safety-ethics');

-- Module 4, Lesson 0: Velika vprašanja o AI
UPDATE course_lessons
SET content = E'# Velika vprašanja o AI\n\nAI odpira vprašanja, na katera človeštvo še nima jasnih odgovorov.\n\n---\n\n## Vprašanje 1: Ali naj AI odloča o ljudeh?\n\n### Primeri:\n\n- AI odloča, kdo dobi posojilo v banki.\n- AI odloča, kdo dobi službo.\n- AI odloča, kdo gre v zapor (v nekaterih državah!).\n\n### Argumenti ZA:\n\n- AI je hitrejša in obdela več podatkov.\n- AI nima slabih dni ali predsodkov (v teoriji).\n- AI je dosledna -- enake podatke vedno oceni enako.\n\n### Argumenti PROTI:\n\n- AI ne razume konteksta človeškega življenja.\n- AI podeduje pristranskost iz preteklih podatkov.\n- Ljudje zaslužimo, da o nas odločajo ljudje.\n\n---\n\n## Vprašanje 2: Ali bo AI vzela delovna mesta?\n\nAI bo spremenila trg dela:\n\n- **Izginotje:** nekatera dela bodo avtomatizirana (blagajnik, voznik).\n- **Sprememba:** mnoga dela se bodo spremenila (zdravnik, učitelj -- AI pomaga).\n- **Nova dela:** nastala bodo nova dela (AI trener, prompt inženir).\n\n---\n\n## Vprašanje 3: Ali lahko AI čuti?\n\nTrenutno NE. AI nima:\n\n- Zavedanja (ne ve, da obstaja).\n- Čustev (ne čuti veselja ali žalosti).\n- Želja (ne želi ničesar).\n\nAI le simulira pogovor -- kot zelo dobra lutka, ki posnema človeka.\n\n---\n\n## Vprašanje 4: Kdo je odgovoren za napake AI?\n\n- Razvijalec? Podjetje? Uporabnik?\n- Če samovozeči avto povzroči nesrečo -- kdo je kriv?\n\n---\n\n## Debata\n\nRazdeli se v 2 skupini in razpravljaj:\n\n**Tema:** "AI naj ima pravico odločati o sprejemu učencev na univerzo."\n\n- Skupina A: ZA.\n- Skupina B: PROTI.\n- 10 minut priprave, 15 minut debata.',
    updated_at = NOW()
WHERE title = 'Velika vprašanja o AI'
  AND course_id = (SELECT id FROM courses WHERE slug = 'ai-safety-ethics');

-- Module 4, Lesson 1: Končni projekt: Moj manifest za odgovorno AI
UPDATE course_lessons
SET content = E'# Končni projekt: Moj manifest za odgovorno AI\n\nČestitke! Prišel si do konca tečaja o AI varnosti in etiki.\n\nTvoj končni projekt je ustvariti **Manifest za odgovorno AI** -- dokument, ki izraža tvoja stališča o tem, kako naj se AI razvija in uporablja.\n\n---\n\n## Struktura manifesta\n\n### 1. Uvod (pol strani)\n\n- Zakaj je ta tema pomembna?\n- Zakaj se TI zavzemaš za odgovorno AI?\n\n### 2. Moja pravila za uporabo AI (1 stran)\n\nNapiši 7--10 osebnih pravil. Primeri:\n\n- "Vedno bom preveril dejstva, ki mi jih poda AI."\n- "Ne bom delil osebnih podatkov z AI sistemi."\n- "AI delo bom vedno označil kot AI delo."\n\n### 3. Pravila za razvijalce AI (1 stran)\n\nNapiši 5--7 pravil za podjetja, ki razvijajo AI:\n\n- "AI mora biti transparentna o svojih omejitvah."\n- "Vsi podatki morajo biti zbrani z dovoljenjem."\n\n### 4. Pravila za družbo (1 stran)\n\nNapiši 3--5 pravil za družbo kot celoto:\n\n- "V šolah se moramo učiti o AI pismenosti."\n- "Zakoni morajo ščititi ljudi pred zlorabo AI."\n\n### 5. Moja vizija prihodnosti (pol strani)\n\n- Kako si predstavljaš svet z AI čez 20 let?\n- Kakšno vlogo bo imel človek?\n- Kaj te navdušuje? Kaj te skrbi?\n\n---\n\n## Kako oddati\n\n### Možnost A: Pisni manifest\n\n- 3--4 strani, lepo oblikovan.\n- Dodaj slike ali ilustracije.\n\n### Možnost B: Video manifest\n\n- 3--5 minut dolg video.\n- Povej svoje misli v kamero.\n- Dodaj primere in slike.\n\n### Možnost C: Plakat\n\n- Velik plakat z glavnimi točkami.\n- Vizualno privlačen.\n- Primeren za razstavo v šoli.\n\n---\n\n## Delitev\n\nSvoj manifest deli z:\n\n- Družino -- skupaj se pogovorite.\n- Sošolci -- primerjajte mnenja.\n- Učiteljem -- mogoče postane del pouka!\n\n**Hvala, da ti ni vseeno za prihodnost AI. Svet potrebuje mlade ljudi, kot si ti, ki razmišljajo kritično in odgovorno!**',
    updated_at = NOW()
WHERE title = 'Končni projekt: Moj manifest za odgovorno AI'
  AND course_id = (SELECT id FROM courses WHERE slug = 'ai-safety-ethics');
